from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class ConceptNode:
    exam: str
    subject: str
    topic: str
    subtopic: str
    concept: str
    keywords: tuple[str, ...]
    prerequisites: tuple[str, ...] = ()

NODES: tuple[ConceptNode, ...] = (
    # ---------------- GATE EE: Engineering Mathematics ----------------
    ConceptNode("GATE_EE","Engineering Mathematics","Linear Algebra","Matrices","Matrix operations",
                ("matrix","matrices","matrix multiplication","transpose")),
    ConceptNode("GATE_EE","Engineering Mathematics","Linear Algebra","Determinants","Determinants and rank",
                ("determinant","det(","rank"),("Matrix operations",)),
    ConceptNode("GATE_EE","Engineering Mathematics","Linear Algebra","Eigen systems","Eigenvalues and eigenvectors",
                ("eigenvalue","eigenvector","characteristic equation"),("Determinants and rank",)),
    ConceptNode("GATE_EE","Engineering Mathematics","Calculus","Differential calculus","Differentiation",
                ("derivative","differentiate","differentiation","maxima","minima","partial derivative")),
    ConceptNode("GATE_EE","Engineering Mathematics","Calculus","Integral calculus","Integration",
                ("integral","integration","definite integral","multiple integral"),("Differentiation",)),
    ConceptNode("GATE_EE","Engineering Mathematics","Calculus","Limits and continuity","Limits and continuity",
                ("limit","continuity","continuous")),
    ConceptNode("GATE_EE","Engineering Mathematics","Differential Equations","Ordinary differential equations","ODE solution",
                ("differential equation","ode","first order","second order"),("Differentiation","Integration")),
    ConceptNode("GATE_EE","Engineering Mathematics","Vector Calculus","Vector differential operators","Gradient divergence curl",
                ("gradient","divergence","curl","nabla","∇")),
    ConceptNode("GATE_EE","Engineering Mathematics","Probability and Statistics","Probability","Conditional probability",
                ("conditional probability","bayes","probability")),
    ConceptNode("GATE_EE","Engineering Mathematics","Probability and Statistics","Random variables","Moments and distributions",
                ("random variable","expectation","mean","variance","distribution","standard deviation")),
    ConceptNode("GATE_EE","Engineering Mathematics","Complex Variables","Complex algebra","Complex numbers",
                ("complex number","conjugate","modulus","argument")),
    ConceptNode("GATE_EE","Engineering Mathematics","Numerical Methods","Root finding","Numerical roots",
                ("newton-raphson","newton raphson","bisection","root finding")),
    ConceptNode("GATE_EE","Engineering Mathematics","Numerical Methods","Interpolation and integration","Numerical approximation",
                ("interpolation","trapezoidal","simpson")),
    ConceptNode("GATE_EE","Engineering Mathematics","Transforms","Laplace/Fourier","Transform methods",
                ("laplace transform","fourier transform","z-transform","z transform")),

    # ---------------- GATE EE: Electrical Engineering ----------------
    ConceptNode("GATE_EE","Electrical Engineering","Electric Circuits","Network laws","KCL and KVL",
                ("kirchhoff","kcl","kvl","node voltage","mesh current")),
    ConceptNode("GATE_EE","Electrical Engineering","Electric Circuits","Network theorems","Thevenin and Norton",
                ("thevenin","norton","superposition","maximum power transfer"),("KCL and KVL",)),
    ConceptNode("GATE_EE","Electrical Engineering","Electric Circuits","AC circuits","Phasor impedance and resonance",
                ("impedance","admittance","phasor","resonance","power factor","rlc"),("KCL and KVL",)),
    ConceptNode("GATE_EE","Electrical Engineering","Signals and Systems","Continuous-time signals","Signal properties",
                ("signal","energy signal","power signal","periodic signal")),
    ConceptNode("GATE_EE","Electrical Engineering","Signals and Systems","LTI systems","Convolution and impulse response",
                ("convolution","impulse response","lti","system response"),("Signal properties",)),
    ConceptNode("GATE_EE","Electrical Engineering","Signals and Systems","Sampling","Sampling theorem",
                ("sampling","nyquist rate","aliasing")),
    ConceptNode("GATE_EE","Electrical Engineering","Electrical Machines","Transformers","Transformer equivalent circuit",
                ("transformer","equivalent circuit","voltage regulation","all day efficiency")),
    ConceptNode("GATE_EE","Electrical Engineering","Electrical Machines","Induction machines","Induction motor",
                ("induction motor","slip","rotor frequency","torque slip")),
    ConceptNode("GATE_EE","Electrical Engineering","Electrical Machines","Synchronous machines","Synchronous machine",
                ("synchronous motor","synchronous generator","alternator","power angle")),
    ConceptNode("GATE_EE","Electrical Engineering","Electrical Machines","DC machines","DC machine",
                ("dc motor","dc generator","dc machine","back emf")),
    ConceptNode("GATE_EE","Electrical Engineering","Power Systems","Power generation and transmission","Transmission lines",
                ("transmission line","abcd parameters","surge impedance","ferranti")),
    ConceptNode("GATE_EE","Electrical Engineering","Power Systems","Power flow","Load flow",
                ("load flow","gauss seidel","newton raphson load flow","bus admittance")),
    ConceptNode("GATE_EE","Electrical Engineering","Power Systems","Fault analysis","Symmetrical components and faults",
                ("fault","short circuit","symmetrical components","positive sequence","negative sequence","zero sequence")),
    ConceptNode("GATE_EE","Electrical Engineering","Power Systems","Protection","Relays and circuit breakers",
                ("relay","circuit breaker","protection","distance relay","differential protection")),
    ConceptNode("GATE_EE","Electrical Engineering","Control Systems","System modeling","Transfer function",
                ("transfer function","block diagram","signal flow graph")),
    ConceptNode("GATE_EE","Electrical Engineering","Control Systems","Time response","Transient response",
                ("rise time","settling time","overshoot","steady state error"),("Transfer function",)),
    ConceptNode("GATE_EE","Electrical Engineering","Control Systems","Stability","Root locus and Routh",
                ("root locus","routh","stability","characteristic equation"),("Transfer function",)),
    ConceptNode("GATE_EE","Electrical Engineering","Control Systems","Frequency response","Bode and Nyquist",
                ("bode","nyquist","gain margin","phase margin"),("Transfer function",)),
    ConceptNode("GATE_EE","Electrical Engineering","Power Electronics","Power semiconductor devices","Switching devices",
                ("thyristor","scr","mosfet","igbt","diode")),
    ConceptNode("GATE_EE","Electrical Engineering","Power Electronics","Converters","Rectifiers",
                ("rectifier","controlled rectifier","firing angle"),("Switching devices",)),
    ConceptNode("GATE_EE","Electrical Engineering","Power Electronics","Converters","Inverters and choppers",
                ("inverter","chopper","pwm","dc-dc"),("Switching devices",)),
    ConceptNode("GATE_EE","Electrical Engineering","Electrical Measurements","Measurement systems","Errors and instruments",
                ("measurement","instrument","error","accuracy","precision")),
    ConceptNode("GATE_EE","Electrical Engineering","Electrical Measurements","Bridges and transducers","Bridge measurement",
                ("wheatstone","bridge","transducer","strain gauge")),
    ConceptNode("GATE_EE","Electrical Engineering","Analog Electronics","Diodes and transistors","Semiconductor circuits",
                ("diode","bjt","transistor","biasing","small signal")),
    ConceptNode("GATE_EE","Electrical Engineering","Analog Electronics","Operational amplifiers","Op-amp circuits",
                ("op-amp","operational amplifier","virtual ground","summing amplifier")),
    ConceptNode("GATE_EE","Electrical Engineering","Digital Electronics","Boolean algebra","Logic simplification",
                ("boolean","k-map","karnaugh","logic gate")),
    ConceptNode("GATE_EE","Electrical Engineering","Digital Electronics","Sequential logic","Flip-flops and counters",
                ("flip flop","flip-flop","counter","register")),
    ConceptNode("GATE_EE","Electrical Engineering","Electromagnetic Fields","Electrostatics","Gauss law and potential",
                ("gauss law","electric field","electric potential","poisson equation","laplace equation")),
    ConceptNode("GATE_EE","Electrical Engineering","Electromagnetic Fields","Magnetostatics","Ampere law and magnetic field",
                ("ampere law","magnetic field","magnetic flux")),
    ConceptNode("GATE_EE","Electrical Engineering","Electromagnetic Fields","Maxwell equations","Electromagnetic waves",
                ("maxwell","electromagnetic wave","poynting")),

    # ---------------- JEE Mathematics ----------------
    ConceptNode("JEE","Mathematics","Sets Relations and Functions","Functions","Functions and mappings",
                ("function","domain","range","one-one","onto","inverse function")),
    ConceptNode("JEE","Mathematics","Complex Numbers and Quadratic Equations","Complex numbers","Complex algebra",
                ("complex number","argand","modulus","argument","|z|")),
    ConceptNode("JEE","Mathematics","Complex Numbers and Quadratic Equations","Quadratic equations","Quadratic roots",
                ("quadratic","roots of equation","discriminant")),
    ConceptNode("JEE","Mathematics","Matrices and Determinants","Matrices","Matrix operations",
                ("matrix","matrices","inverse matrix")),
    ConceptNode("JEE","Mathematics","Matrices and Determinants","Determinants","Determinants",
                ("determinant","det("),("Matrix operations",)),
    ConceptNode("JEE","Mathematics","Permutations and Combinations","Counting","Combinatorics",
                ("permutation","combination","arrangement","arrangements","selection")),
    ConceptNode("JEE","Mathematics","Binomial Theorem","Expansion","Binomial coefficients",
                ("binomial","coefficient","middle term")),
    ConceptNode("JEE","Mathematics","Sequence and Series","Progressions","AP GP and series",
                ("arithmetic progression","geometric progression","sequence","series","ap","gp")),
    ConceptNode("JEE","Mathematics","Limits Continuity and Differentiability","Limits","Limits",
                ("limit","indeterminate")),
    ConceptNode("JEE","Mathematics","Limits Continuity and Differentiability","Differentiation","Derivative",
                ("derivative","differentiate","differentiability","differentiable"),("Limits",)),
    ConceptNode("JEE","Mathematics","Integral Calculus","Indefinite integration","Integration",
                ("indefinite integral","integrate","integration","area bounded")),
    ConceptNode("JEE","Mathematics","Integral Calculus","Definite integration","Definite integrals",
                ("definite integral","area under curve"),("Integration",)),
    ConceptNode("JEE","Mathematics","Differential Equations","ODE","Differential equation",
                ("differential equation","order and degree","dy/dx")),
    ConceptNode("JEE","Mathematics","Coordinate Geometry","Straight lines","Straight line",
                ("straight line","slope","distance from line")),
    ConceptNode("JEE","Mathematics","Coordinate Geometry","Circle","Circle geometry",
                ("circle","chord","tangent")),
    ConceptNode("JEE","Mathematics","Coordinate Geometry","Conic sections","Parabola ellipse hyperbola",
                ("parabola","ellipse","hyperbola","conic")),
    ConceptNode("JEE","Mathematics","Three Dimensional Geometry","3D coordinates","Line and plane",
                ("3d","three dimensional","direction cosine","plane","planes","skew lines","angle between two planes","normal vectors")),
    ConceptNode("JEE","Mathematics","Vector Algebra","Vectors","Vector products",
                ("vector","vectors","dot product","cross product","scalar triple")),
    ConceptNode("JEE","Mathematics","Trigonometry","Trigonometric functions","Identities and equations",
                ("trigonometry","trigonometric","sin","cos","tan")),
    ConceptNode("JEE","Mathematics","Probability and Statistics","Probability","Probability",
                ("probability","bayes","conditional probability","p(")),
    ConceptNode("JEE","Mathematics","Probability and Statistics","Statistics","Mean and variance",
                ("mean","variance","standard deviation","statistics")),

    # ---------------- JEE Physics ----------------
    ConceptNode("JEE","Physics","Units and Measurements","Measurement","Dimensions and errors",
                ("dimensions","dimensional","significant figures","measurement error","uncertainty")),
    ConceptNode("JEE","Physics","Kinematics","Motion in one/two dimensions","Kinematics",
                ("velocity","acceleration","displacement","projectile","kinematics")),
    ConceptNode("JEE","Physics","Laws of Motion","Newton laws","Force and friction",
                ("newton's law","force","friction","free-body","free body"),("Kinematics",)),
    ConceptNode("JEE","Physics","Work Energy and Power","Energy","Work-energy theorem",
                ("work energy","kinetic energy","potential energy","power","work done")),
    ConceptNode("JEE","Physics","Rotational Motion","Rigid body","Rotation and torque",
                ("torque","angular momentum","moment of inertia","rolling","rotational","rotates","rotational kinetic energy")),
    ConceptNode("JEE","Physics","Gravitation","Gravity","Gravitational field and orbit",
                ("gravitation","gravitational","escape velocity","satellite")),
    ConceptNode("JEE","Physics","Properties of Matter","Fluids","Fluid mechanics",
                ("viscosity","surface tension","bernoulli","fluid","pressure")),
    ConceptNode("JEE","Physics","Thermodynamics","Thermal physics","First/second law",
                ("thermodynamics","entropy","heat engine","isothermal","isothermal expansion","adiabatic")),
    ConceptNode("JEE","Physics","Kinetic Theory","Gas model","Kinetic theory",
                ("kinetic theory","rms speed","ideal gas")),
    ConceptNode("JEE","Physics","Oscillations and Waves","SHM","Simple harmonic motion",
                ("simple harmonic","shm","oscillation","spring mass")),
    ConceptNode("JEE","Physics","Oscillations and Waves","Waves","Wave motion",
                ("wave","standing wave","doppler","sound","resonance")),
    ConceptNode("JEE","Physics","Electrostatics","Electric charges and fields","Coulomb/Gauss",
                ("coulomb","electric field","electric flux","gauss law")),
    ConceptNode("JEE","Physics","Electrostatics","Potential and capacitance","Capacitors",
                ("electric potential","capacitance","capacitor")),
    ConceptNode("JEE","Physics","Current Electricity","DC circuits","Current and resistance",
                ("current electricity","resistance","resistivity","kirchhoff","potentiometer","battery","ohm")),
    ConceptNode("JEE","Physics","Magnetic Effects of Current","Magnetism","Lorentz force and Biot-Savart",
                ("lorentz","biot-savart","magnetic field","ampere law")),
    ConceptNode("JEE","Physics","Electromagnetic Induction","Induction","Faraday and Lenz laws",
                ("faraday","lenz","electromagnetic induction","induced emf")),
    ConceptNode("JEE","Physics","Alternating Current","AC","RLC and resonance",
                ("alternating current","ac circuit","rlc","resonance")),
    ConceptNode("JEE","Physics","Electromagnetic Waves","EM waves","Electromagnetic spectrum",
                ("electromagnetic wave","em wave","spectrum","ultraviolet","infrared")),
    ConceptNode("JEE","Physics","Ray Optics","Geometrical optics","Mirrors and lenses",
                ("ray optics","lens","mirror","refraction","snell")),
    ConceptNode("JEE","Physics","Wave Optics","Interference/diffraction","Wave optics",
                ("interference","diffraction","polarization","young double slit","young double-slit","double-slit")),
    ConceptNode("JEE","Physics","Dual Nature","Quantum effects","Photoelectric effect",
                ("photoelectric","de broglie","dual nature")),
    ConceptNode("JEE","Physics","Atoms and Nuclei","Atomic/nuclear physics","Bohr radioactivity",
                ("bohr","radioactive","radioactivity","nucleus","binding energy")),
    ConceptNode("JEE","Physics","Semiconductor Electronics","Semiconductors","Diode and transistor",
                ("semiconductor","pn junction","diode","transistor","logic gate")),
)

def nodes_for(exam: str | None = None, subject: str | None = None) -> tuple[ConceptNode, ...]:
    return tuple(n for n in NODES if (exam is None or n.exam == exam) and (subject is None or n.subject == subject))
